In [18]:
import pandas as pd
df=pd.read_csv('SMSSpamCollection.txt',sep='\t',names=['label','message'])
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [19]:
df=df.drop(columns='label')
df.head()

                                             message
0  Go until jurong point, crazy.. Available only ...
1                      Ok lar... Joking wif u oni...
2  Free entry in 2 a wkly comp to win FA Cup fina...
3  U dun say so early hor... U c already then say...
4  Nah I don't think he goes to usf, he lives aro...

In [20]:
df['clean_message']=df['message'].str.lower()
df.head()

,message,clean_message
0,"Go until jurong point, crazy.. Available only ...","go until jurong point, crazy.. available only ..."
1,Ok lar... Joking wif u oni...,ok lar... joking wif u oni...
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...
3,U dun say so early hor... U c already then say...,u dun say so early hor... u c already then say...
4,"Nah I don't think he goes to usf, he lives aro...","nah i don't think he goes to usf, he lives aro..."

In [21]:

import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [22]:
def remove_punctuation(text):
    punctuation=string.punctuation
    return text.translate(str.maketrans('','',punctuation))

In [24]:
df['clean_message']=df['clean_message'].apply(lambda x: remove_punctuation(x))
df.head()

,message,clean_message
0,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...
1,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...
3,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say
4,"Nah I don't think he goes to usf, he lives aro...",nah i dont think he goes to usf he lives aroun...

In [25]:
from nltk.corpus import stopwords
", ".join(stopwords.words('english'))

"a, about, above, after, again, against, ain, all, am, an, and, any, are, aren, aren't, as, at, be, because, been, before, being, below, between, both, but, by, can, couldn, couldn't, d, did, didn, didn't, do, does, doesn, doesn't, doing, don, don't, down, during, each, few, for, from, further, had, hadn, hadn't, has, hasn, hasn't, have, haven, haven't, having, he, he'd, he'll, her, here, hers, herself, he's, him, himself, his, how, i, i'd, if, i'll, i'm, in, into, is, isn, isn't, it, it'd, it'll, it's, its, itself, i've, just, ll, m, ma, me, mightn, mightn't, more, most, mustn, mustn't, my, myself, needn, needn't, no, nor, not, now, o, of, off, on, once, only, or, other, our, ours, ourselves, out, over, own, re, s, same, shan, shan't, she, she'd, she'll, she's, should, shouldn, shouldn't, should've, so, some, such, t, than, that, that'll, the, their, theirs, them, themselves, then, there, these, they, they'd, they'll, they're, they've, this, those, through, to, too, under, until, up, ve, very, was, wasn, wasn't, we, we'd, we'll, we're, were, weren, weren't, we've, what, when, where, which, while, who, whom, why, will, with, won, won't, wouldn, wouldn't, y, you, you'd, you'll, your, you're, yours, yourself, yourselves, you've"

In [26]:
STOPWORDS = set(stopwords.words('english'))
def remove_stopwords(text):
    return " ".join([word for word in text.split() if word not in STOPWORDS])

In [27]:
df['clean_message']=df['message'].apply(lambda x: remove_stopwords(x))
df.head()

,message,clean_message
0,"Go until jurong point, crazy.. Available only ...","Go jurong point, crazy.. Available bugis n gre..."
1,Ok lar... Joking wif u oni...,Ok lar... Joking wif u oni...
2,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry 2 wkly comp win FA Cup final tkts 2...
3,U dun say so early hor... U c already then say...,U dun say early hor... U c already say...
4,"Nah I don't think he goes to usf, he lives aro...","Nah I think goes usf, lives around though"

In [28]:
from collections import Counter
word_count = Counter()
for text in df['clean_message']:
    for word in text.split():
        word_count[word] += 1
        
word_count.most_common(10)

[('I', 1469),
 ('u', 698),
 ('2', 457),
 ('call', 376),
 ('get', 326),
 ('U', 300),
 ('ur', 297),
 ("I'm", 286),
 ('&lt;#&gt;', 276),
 ('You', 263)]

In [29]:
FREQUENT_WORDS = set(word for (word, wc) in word_count.most_common(3))
def remove_freq_words(text):
    return " ".join([word for word in text.split() if word not in FREQUENT_WORDS])

In [30]:
df['clean_message'] = df['clean_message'].apply(lambda x: remove_freq_words(x))
df.head()

,message,clean_message
0,"Go until jurong point, crazy.. Available only ...","Go jurong point, crazy.. Available bugis n gre..."
1,Ok lar... Joking wif u oni...,Ok lar... Joking wif oni...
2,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry wkly comp win FA Cup final tkts 21s...
3,U dun say so early hor... U c already then say...,U dun say early hor... U c already say...
4,"Nah I don't think he goes to usf, he lives aro...","Nah think goes usf, lives around though"

In [31]:

RARE_WORDS = set(word for (word, wc) in word_count.most_common()[:-10:-1])
RARE_WORDS
def remove_rare_words(text):
    return " ".join([word for word in text.split() if word not in RARE_WORDS])

In [32]:
df['clean_message'] = df['clean_message'].apply(lambda x: remove_rare_words(x))
df.head()

,message,clean_message
0,"Go until jurong point, crazy.. Available only ...","Go jurong point, crazy.. Available bugis n gre..."
1,Ok lar... Joking wif u oni...,Ok lar... Joking wif oni...
2,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry wkly comp win FA Cup final tkts 21s...
3,U dun say so early hor... U c already then say...,U dun say early hor... U c already say...
4,"Nah I don't think he goes to usf, he lives aro...","Nah think goes usf, lives around though"

In [33]:
import re
def remove_spl_chars(text):
    text = re.sub('[^a-zA-Z0-9]', ' ', text)
    text = re.sub('\s+', ' ', text)
    return text

<>:4: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:4: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\ITC\AppData\Local\Temp\ipykernel_19724\688201358.py:4: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  text = re.sub('\s+', ' ', text)

In [34]:
df['clean_message']=df['clean_message'].apply(lambda x: remove_spl_chars(x))
df.head()

,message,clean_message
0,"Go until jurong point, crazy.. Available only ...",Go jurong point crazy Available bugis n great ...
1,Ok lar... Joking wif u oni...,Ok lar Joking wif oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry wkly comp win FA Cup final tkts 21s...
3,U dun say so early hor... U c already then say...,U dun say early hor U c already say
4,"Nah I don't think he goes to usf, he lives aro...",Nah think goes usf lives around though

In [35]:
from nltk import pos_tag
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
wordnet_map = {"N":wordnet.NOUN, "V": wordnet.VERB, "J": wordnet.ADJ, "R": wordnet.ADV}

def lemmatize_words(text):
    # find pos tags
    pos_text = pos_tag(text.split())
    return " ".join([lemmatizer.lemmatize(word, wordnet_map.get(pos[0], wordnet.NOUN)) for word, pos in pos_text])

In [36]:

wordnet.NOUN

'n'

In [37]:
df['lemmatized_text'] = df['clean_message'].apply(lambda x: lemmatize_words(x))
df.head()

,message,clean_message,lemmatized_text
0,"Go until jurong point, crazy.. Available only ...",Go jurong point crazy Available bugis n great ...,Go jurong point crazy Available bugis n great ...
1,Ok lar... Joking wif u oni...,Ok lar Joking wif oni,Ok lar Joking wif oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry wkly comp win FA Cup final tkts 21s...,Free entry wkly comp win FA Cup final tkts 21s...
3,U dun say so early hor... U c already then say...,U dun say early hor U c already say,U dun say early hor U c already say
4,"Nah I don't think he goes to usf, he lives aro...",Nah think goes usf lives around though,Nah think go usf life around though

In [38]:
df.sample(frac=1).head(10)

,message,clean_message,lemmatized_text
2530,Can you just come in for a sec? There's somebo...,Can come sec There s somebody want see,Can come sec There s somebody want see
3238,Ron say fri leh. N he said ding tai feng cant ...,Ron say fri leh N said ding tai feng cant make...,Ron say fri leh N say ding tai feng cant make ...
1410,Where at were hungry too,Where hungry,Where hungry
5546,Ic. There are a lotta childporn cars then.,Ic There lotta childporn cars then,Ic There lotta childporn car then
4831,"The word ""Checkmate"" in chess comes from the P...",The word Checkmate chess comes Persian phrase ...,The word Checkmate chess come Persian phrase S...
462,Great. Never been better. Each day gives even ...,Great Never better Each day gives even reasons...,Great Never good Each day give even reason tha...
4101,I not at home now lei...,home lei,home lei
3571,Customer Loyalty Offer:The NEW Nokia6650 Mobil...,Customer Loyalty Offer The NEW Nokia6650 Mobil...,Customer Loyalty Offer The NEW Nokia6650 Mobil...
2315,Also that chat was awesome but don't make it r...,Also chat awesome make regular unless see person,Also chat awesome make regular unless see person
5008,Oh k. . I will come tomorrow,Oh k come tomorrow,Oh k come tomorrow

In [41]:
from spellchecker import SpellChecker

spell = SpellChecker()

def correct_spellings(text):
    corrected_text = []
    misspelled_text = spell.unknown(text.split())
    
    for word in text.split():
        if word in misspelled_text:
            corrected_word = spell.correction(word)
            if corrected_word is not None:
                corrected_text.append(corrected_word)
            else:
                corrected_text.append(word)  # لو مش قادر يصحح، خلي الكلمة زي ما هي
        else:
            corrected_text.append(word)
            
    return " ".join(corrected_text)

In [42]:
df['clean_message']=df['clean_message'].apply(lambda x: correct_spellings(x))
df.head()

,message,clean_message,lemmatized_text
0,"Go until jurong point, crazy.. Available only ...",Go wrong point crazy Available bugs n great wo...,Go jurong point crazy Available bugis n great ...
1,Ok lar... Joking wif u oni...,Ok lar Joking if on,Ok lar Joking wif oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry wily come win FA Cup final tits jus...,Free entry wkly comp win FA Cup final tkts 21s...
3,U dun say so early hor... U c already then say...,U dun say early for U c already say,U dun say early hor U c already say
4,"Nah I don't think he goes to usf, he lives aro...",Nah think goes us lives around though,Nah think go usf life around though